# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96ac3e63640760b959a6a3500ae948e961302d77960d52f080a24e2c53dbbba7d9e35e0b4ba5b5610fe03087e0d46d969e8c1c71cc21498fe7086b05458ea939

test:
  secret_key_base: 9076af61de0a73029f575f13c190f7d5f9ddd2f5aaee54f5f7048434d3768869536a0073f67d7f89d4f2bcc31b5caaee319e2216b0672f7c84791daf77e6887f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
